# Generated by Django 2.2.4 on 2019-08-07 17:43

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.ftp


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('salario', models.IntegerField(default=0)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('curriculo', models.FileField(storage=storages.backends.ftp.FTPStorage(), upload_to='curriculos/')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.Vaga')),
            ],
        ),
    ]
